# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "ohci_pci" "sd_mod" "sr_mod" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b40557b6-ffeb-4393-8555-c36a3822d1c8";
      fsType = "btrfs";
      options = [ "compress=lzo" "subvol=root" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/b40557b6-ffeb-4393-8555-c36a3822d1c8";
      fsType = "btrfs";
      options = [ "compress=lzo" "subvol=home" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/0373196f-541e-4e58-a6e7-96c28d74ee0f"; }
    ];

  nix.maxJobs = lib.mkDefault 2;
  virtualisation.virtualbox.guest.enable = true;
}
