#!/usr/bin/env bash

VERSION="nixos-22.05"

if ! sudo nix-channel --list | grep "${VERSION}" >/dev/null; then
  echo 'adding channel...'
  sudo nix-channel --remove nixos
  sudo nix-channel --add "https://nixos.org/channels/${VERSION}" nixos || exit 1
  sudo nix-channel --update nixos
fi
